---
title: "Flattening CP Partner Grant Areas"
author: "Clarissa Boyajian"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(rosm)
```

# Creating City Plants Partner Grant Areas

## Creating Los Angeles Outline

```{r}
la_cd_outline <- st_read(dsn = "data/LA_City_Council_Districts_(Adopted_2012).kml")

la_city_outline <- st_read(dsn = "data/City_Boundary.kml") %>% 
  mutate(Name = "City of LA Outline") %>% 
  select("Name", "geometry")

tm_shape(la_cd_outline) +
  tm_polygons(col = "Name")

tm_shape(la_city_outline) +
  tm_polygons()
```

## Creating KYCC Grant Areas

```{r KYCC grants}
kycc_area_full <- st_read(dsn = "data/kycc.kml") %>% 
  select("Name", "geometry")

# Remove and create CalFire-Jefferson grant
kycc_calfire_jefferson_rough <- st_read(dsn = "data/kycc_calfire-jeffereson.kml")

kycc_calfire_jefferson <- st_intersection(kycc_area_full, kycc_calfire_jefferson_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "KYCC_CalFire-Jefferson")

kycc_area <- st_difference(kycc_area_full, kycc_calfire_jefferson_rough)

# Remove and create CalFire-SLA grant
kycc_calfire_sla_rough <- st_read(dsn = "data/kycc_calfire-sla.kml")

kycc_calfire_sla <- st_intersection(kycc_area, kycc_calfire_sla_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "KYCC_CalFire-SLA")

kycc_area <- st_difference(kycc_area, kycc_calfire_sla_rough)

# Remove and create CalFire-Ambassadors grant
kycc_calfire_ambassadors_rough <- st_read(dsn = "data/kycc_calfire-ambassadors.kml")

kycc_calfire_ambassadors <- st_intersection(kycc_area, kycc_calfire_ambassadors_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "KYCC_CalFire-Ambassador")

kycc_area <- st_difference(kycc_area, kycc_calfire_ambassadors_rough)

# Remove and create CalFire-Density grant
kycc_calfire_density_rough <- st_read(dsn = "data/kycc_calfire-density.kml")

kycc_calfire_density <- st_intersection(kycc_area, kycc_calfire_density_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "KYCC_CalFire-Density")

kycc_area <- st_difference(kycc_area, kycc_calfire_density_rough)

# Create KYCC all grants df
kycc_grants <- rbind(kycc_calfire_jefferson, kycc_calfire_sla, kycc_calfire_ambassadors, kycc_calfire_density)

# Map check
tm_shape(kycc_area_full) +
  tm_polygons(col = "grey", alpha = 0.5) +
  tm_shape(kycc_grants) +
  tm_borders(col = "darkred") +
  tm_fill(col = "Name") +
  tm_layout(legend.position = c("left", "bottom"))
```

```{r eval=FALSE}
# Save KYCC grants to shp and kml
st_write(kycc_grants, "flattened_grants/KYCC_Grants.shp", append = FALSE)

st_write(kycc_grants, "flattened_grants/KYCC_Grants.kml", append = FALSE)
```

## Creating TP Grant Areas

```{r}
tp_grants <- st_read(dsn = "data/tp.kml") %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "TreePeople_Watts-Rising")

# Map check
tm_shape(tp_grants) +
  tm_polygons()
```

## Creating NET Grant Areas

```{r}
net_area_full <- st_read(dsn = "data/net.kml") %>% 
  select("Name", "geometry")

# Remove and create 


# Remove and create CalFire-Jefferson grant
#kycc_calfire_jefferson_rough <- st_read(dsn = "data/kycc_calfire-jeffereson.kml")

#kycc_calfire_jefferson <- st_intersection(kycc_area_full, kycc_calfire_jefferson_rough) %>% 
#  select("Name", "geometry") %>% 
#  mutate(Name = "KYCC_CalFire-Jefferson")

#kycc_area <- st_difference(kycc_area_full, kycc_calfire_jefferson_rough)

# Remove and create CalFire-SLA grant
#kycc_calfire_sla_rough <- st_read(dsn = "data/kycc_calfire-sla.kml")

#kycc_calfire_sla <- st_intersection(kycc_area, kycc_calfire_sla_rough) %>% 
#  select("Name", "geometry") %>% 
#  mutate(Name = "KYCC_CalFire-SLA")

#kycc_area <- st_difference(kycc_area, kycc_calfire_sla_rough)

# Remove and create CalFire-Ambassadors grant
#kycc_calfire_ambassadors_rough <- st_read(dsn = "data/kycc_calfire-ambassadors.kml")

#kycc_calfire_ambassadors <- st_intersection(kycc_area, kycc_calfire_ambassadors_rough) %>% 
#  select("Name", "geometry") %>% 
#  mutate(Name = "KYCC_CalFire-Ambassador")

#kycc_area <- st_difference(kycc_area, kycc_calfire_ambassadors_rough)

# Remove and create CalFire-Density grant
#kycc_calfire_density_rough <- st_read(dsn = "data/kycc_calfire-density.kml")

#kycc_calfire_density <- st_intersection(kycc_area, kycc_calfire_density_rough) %>% 
#  select("Name", "geometry") %>% 
#  mutate(Name = "KYCC_CalFire-Density")

#kycc_area <- st_difference(kycc_area, kycc_calfire_density_rough)

# Create KYCC all grants df
#kycc_grants <- rbind(kycc_calfire_jefferson, kycc_calfire_sla, kycc_calfire_ambassadors, kycc_calfire_density)






# Map check
tm_shape(kycc_area_full) +
  tm_polygons(col = "grey", alpha = 0.5) +
  tm_shape(kycc_grants) +
  tm_borders(col = "darkred") +
  tm_fill(col = "Name") +
  tm_layout(legend.position = c("left", "bottom"))
```



## Combining and Mapping All Grants

```{r}
all_partner_grants <- rbind(kycc_grants, tp_grants)

tm_shape(la_city_outline) +
  tm_polygons(col = "lightgrey", alpha = 0.5) +
  tm_shape(all_partner_grants) +
  tm_borders(col = "black", alpha = 0.5) +
  tm_fill(col = "Name")

```











