---
title: "Flattening Grant Areas - City Plants"
author: "Clarissa Boyajian"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Load libraries}
library(tidyverse)
library(sf)
library(tmap)
library(rosm)
```

# Creating City Plants Partner Planting Boundaries


## Creating Los Angeles Outline

```{r Load LA City Outline}
la_cd_outline <- st_read(dsn = "data_general/LA_City_Council_Districts_(Adopted_2012).kml") %>% 
  st_union()

la_city_outline <- st_read(dsn = "data_general/City_Boundary.kml") %>% 
  mutate(Name = "City of LA Outline") %>% 
  select("Name", "geometry")

tmap_mode("plot") +
tm_shape(la_city_outline) +
  tm_polygons()
```


## Creating NET Area

```{r NET}
# Create Watts Rising portion of NET
net_watts_rough <- st_read(dsn = "partner_area_data/NET_Watts.kml") %>% 
  select("Name", "geometry")

net_watts <- st_intersection(la_city_outline, net_watts_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "NET")

la_city_outline_smaller <- st_difference(la_city_outline, net_watts_rough) %>% 
  select("Name", "geometry")


# Adding in SCLA Greening to NET
net_scla_greening_rough <- st_read(dsn = "partner_area_data/net_scla-greening.kml") %>% 
  select("Name", "geometry")

net_scla_greening <- st_intersection(la_city_outline_smaller, net_scla_greening_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "NET")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, net_scla_greening_rough) %>% 
  select("Name", "geometry")


# Adding in main NET Area
net_rough <- st_read(dsn = "partner_area_data/NET.kml") %>% 
  select("Name", "geometry")

net_main <- st_intersection(la_city_outline_smaller, net_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "NET")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, net_rough) %>% 
  select("Name", "geometry")


# Combining all areas
net_temp <- st_union(net_main, net_watts) %>% 
  select("geometry") %>% 
  mutate(Name = "NET", .before = "geometry")

net <- st_union(net_temp, net_scla_greening) %>% 
  select("geometry") %>% 
  mutate(Name = "NET", .before = "geometry")


# Map check
tm_shape(net) +
  tm_polygons()

tm_shape(la_city_outline_smaller) +
  tm_polygons()
```


## Creating LACC Areas

```{r LACC_ELA}
# Create main portion of LACC_ELA
lacc_rough <- st_read(dsn = "partner_area_data/LACC.kml", layer = "LACC") %>% 
  select("Name", "geometry")

lacc_ela_main <- st_intersection(la_city_outline_smaller, lacc_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "LACC_ELA")
  
la_city_outline_smaller <- st_difference(la_city_outline_smaller, lacc_rough) %>% 
  select("Name", "geometry")


# Add in South LA portion of LACC_ELA
lacc_ela_sla_rough <- st_read(dsn = "partner_area_data/LACC_ELA.kml") %>% 
  select("Name", "geometry")

lacc_ela_sla <- st_intersection(la_city_outline_smaller, lacc_ela_sla_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "LACC_ELA")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, lacc_ela_sla_rough) %>% 
  select("Name", "geometry")

lacc_ela <- st_union(lacc_ela_main, lacc_ela_sla) %>% 
  select("geometry") %>% 
  mutate(Name = "LACC_ELA", .before = "geometry")


# Map check
tm_shape(lacc_ela) +
  tm_polygons()

tm_shape(la_city_outline_smaller) +
  tm_polygons()
```

```{r LACC_Valley}
# Create first portion of LACC_Valley
lacc_valley_main_rough <- st_read(dsn = "partner_area_data/LACC_Valley.kml") %>% 
  select("Name", "geometry")

lacc_valley_main <- st_intersection(la_city_outline_smaller, lacc_valley_main_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "LACC_Valley")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, lacc_valley_main_rough) %>% 
  select("Name", "geometry")


# Adding in TCC project to LACC_Valley
lacc_valley_tcc_rough <- st_read(dsn = "partner_area_data/lacc-valley_tcc-project.kml") %>% 
  select("Name", "geometry")

lacc_valley_tcc <- st_intersection(la_city_outline_smaller, lacc_valley_tcc_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "LACC_ELA")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, lacc_valley_tcc_rough) %>% 
  select("Name", "geometry")

lacc_valley <- st_union(lacc_valley_main, lacc_valley_tcc) %>% 
  select("geometry") %>% 
  mutate(Name = "LACC_ELA", .before = "geometry")


# Map check
tm_shape(lacc_valley) +
  tm_polygons()

tm_shape(la_city_outline_smaller) +
  tm_polygons()
```

## Creating KYCC Area

```{r KYCC}
# Create KYCC area
kycc_rough <- st_read(dsn = "partner_area_data/KYCC.kml") %>% 
  select("Name", "geometry")

kycc <- st_intersection(la_city_outline_smaller, kycc_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "KYCC")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, kycc_rough) %>% 
  select("Name", "geometry")


# Map check
tm_shape(kycc) +
  tm_polygons()

tm_shape(la_city_outline_smaller) +
  tm_polygons()
```


## Creating HLABT Area

```{r HLABT}
# CreateHLABT area
hlabt_rough <- st_read(dsn = "partner_area_data/HLABT.kml") %>% 
  select("Name", "geometry")

hlabt <- st_intersection(la_city_outline_smaller, hlabt_rough) %>% 
  select("Name", "geometry") %>% 
  mutate(Name = "HLABT")

la_city_outline_smaller <- st_difference(la_city_outline_smaller, hlabt_rough) %>% 
  select("Name", "geometry")


# Map check
tm_shape(hlabt) +
  tm_polygons()

tm_shape(la_city_outline_smaller) +
  tm_polygons()
```

## Creating TP Area

```{r TreePeople}
# Create TP Watts Rising area
tp <- la_city_outline_smaller %>% 
  mutate(Name = "TreePeople")


# Map check
tm_shape(tp) +
  tm_polygons()
```


## Combining All Partner Areas

```{r City Plants Partner Planting Areas}
# Combine all partner areas into one df
city_plants_partner_boundaries <- rbind(lacc_ela, lacc_valley, net, kycc, hlabt, tp)


# Map check
tm_shape(city_plants_partner_boundaries) +
  tm_polygons(col = "Name")
```



# Saving to shp and kml Files (NOTE: have to run manually)

```{r Save Areas to ShapeFile and KML, eval=FALSE}
# Saving all partner areas to SHP
st_write(city_plants_partner_boundaries, "partner_area_flattened/City_Plants_Partner_Planting_Boundaries.shp", append = FALSE)

# Saving all partner areas to KML
st_write(city_plants_partner_boundaries, "partner_area_flattened/City_Plants_Partner_Planting_Boundaries.kml", append = FALSE)


# Saving each partner area to KML
st_write(lacc_ela, "grant_area_data/lacc_ela.kml", append = FALSE)
st_write(lacc_valley, "grant_area_data/lacc_valley.kml", append = FALSE)
st_write(kycc, "grant_area_data/kycc.kml", append = FALSE)
st_write(net, "grant_area_data/net.kml", append = FALSE)
st_write(hlabt, "grant_area_data/hlabt.kml", append = FALSE)
st_write(tp, "grant_area_data/tp.kml", append = FALSE)
```



# Mapping All City Plants Nonprofit Planting Partner Areas

```{r Create LA Base Map, warning = FALSE}
# Create Los Angeles bounding box
bbox_poly = st_polygon(list(rbind(c(-118.735904, 34.349321), #left, top
                                  c(-118.735904, 34.349321), #right, top
                                  c(-118.152680, 33.704487), #right, bottom
                                  c(-118.152680, 33.704487), #left, bottom
                                  c(-118.735904, 34.349321))) #left, top
                       )

LA_zoom <- osm.raster(st_bbox(st_sfc(bbox_poly, 
                                     crs = 4326)))


# Create zoom-able map of all partner areas
tmap_mode("view") +
  tm_shape(LA_zoom) +
  tm_rgb() +
  tm_shape(city_plants_partner_boundaries) +
  tm_fill(col = "Name", alpha = 0.4) +
  tm_borders(col = "black", alpha = 0.5)
```

